version: "3.8"

services:

  web:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    image: backend/charity/charity_django:1.0.0
    command: /start

    volumes:
      - .:/app
      - ./static:/static
    expose:
      - 8000
    env_file:
      - ./.env/.dev-sample
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_DB=postgres"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"

volumes:
  postgres_data:
